# Site settings
title: Jelly Chinese Version
email: web_support@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll" # the subpath of your site, e.g. /blog/
url: "http://xinerd.github.io/" # the base hostname & protocol for your site
twitter_username: xinerd
github_username:  xinerd

# Build settings
markdown: kramdown
